{% set name = "langchain-mongodb" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_mongodb-{{ version }}.tar.gz
  sha256: 1c9bd59ac45131b5d435f6bc8aeccce6eaca39d260134ad64fdac1951fbf3d32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - lark <2.0.0,>=1.1.9
    - python >={{ python_min }}
    - pymongo >=4.6.1
    - langchain-core >=0.3
    - numpy >=1.26
    - langchain >=0.3
    - langchain-text-splitters >=0.3
    - motor

test:
  imports:
    - langchain_mongodb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting MongoDB and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
