{% set name = "langchain-mongodb" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_mongodb-{{ version }}.tar.gz
  sha256: b17af5e910c6f0e5b1b121006ddd2ae0d5a07295042a8e18ac4ced32c0be8fa6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - langchain-classic >=1.0
    - lark <2.0.0,>=1.1.9
    - python >={{ python_min }}
    - pymongo >=4.6.1
    - langchain-core >=1.0
    - numpy >=1.26
    - langchain >=1.0
    - langchain-text-splitters >=1.0
    - motor

test:
  imports:
    - langchain_mongodb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting MongoDB and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
